In [8]:
import numpy as np

a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
print(a.ndim, b.shape, a.dtype, a.itemsize, a.nbytes, a.size)
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

1 (2, 3) int32 4 12 3
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(np.zeros((2,3)))
print(np.ones((4,2,2), dtype='int32'))
print(np.full((2,2), 99))
print(np.full_like(a, 4))
print(np.random.rand(4,2))
print(np.random.randint(-4,8, size=(3,3)))
print(np.identity(5))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[99 99]
 [99 99]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[0.54070799 0.10035751]
 [0.56723492 0.31078656]
 [0.3073264  0.74639682]
 [0.49000985 0.70086462]]
[[ 0  1  6]
 [ 4 -1  7]
 [-3 -2  7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)
a = np.array([1,2,3,4])
print(a)

[1 2 3]
[100   2   3]
[1 2 3 4]


In [15]:
b = np.array([1,0,1,0])

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [16]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [17]:
c = np.identity(3)
np.linalg.det(c)

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.min(stats)

np.max(stats, axis=1)

np.sum(stats, axis=0)

array([5, 7, 9])

In [19]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
