In [ ]:
import torch

x = torch.empty(1) #scalar
print("empty 1", x)
x = torch.empty(3) #vector
print("empty 3", x)
x = torch.empty(2,3) #matrix
print("empty 2,3", x)
x = torch.empty(2,3,3) #tensor, 3d
print("empty 2,3,3", x)
x = torch.empty(2,3,3,4) #tensor, 4d
print("empty 2,3,3,4", x)

x = torch.rand(2,3)
print("rand 2,3", x)
x = torch.zeros(2,3)
print("zeros 2,3", x)
x = torch.ones(2,3)
print("ones 2,3", x)

empty 1 tensor([-3.2432e+25])
empty 3 tensor([ 2.4916e-14,  0.0000e+00, -5.7711e+21])
empty 2,3 tensor([[-5.7712e+21,  4.5176e-41, -5.7712e+21],
        [ 4.5176e-41,  4.4842e-44,  0.0000e+00]])
empty 2,3,3 tensor([[[ 0.0000e+00,  0.0000e+00,  2.7915e-14],
         [ 0.0000e+00,  3.4388e-15,  0.0000e+00],
         [-3.6059e+25,  4.5175e-41,  1.4013e-45]],

        [[ 0.0000e+00,  7.0065e-45,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
empty 2,3,3,4 tensor([[[[ 2.5074e-14,  0.0000e+00,  2.7909e-14,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 1.5695e-43,  0.0000e+00,  2.6905e-43,  0.0000e+00],
          [-1.9433e+05,  4.5176e-41,  0.0000e+00,  1.4013e-45],
          [ 2.7920e-14,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  2.5156e-14,  0.0000e+00],
          [ 3.4388e-15,

In [ ]:
print("size" , x.size())
print("shape" , x.shape[0])
print(x.dtype)
x = torch.rand(2,3, dtype=torch.float32)
print(x.dtype)

size torch.Size([2, 3])
shape 2
torch.float32
torch.float32


In [ ]:
x = torch.tensor([0,1,4])
print(x)
x = torch.tensor([0,1,4.2], requires_grad=True)
#this will tell pytorch that we need to calculate the gradient of this tensor in future
#i.e., this is a variable in our model that we have to optimize
print(x)

tensor([0, 1, 4])
tensor([0.0000, 1.0000, 4.2000], requires_grad=True)


In [ ]:
x = torch.ones(2,2)
y = torch.rand(2,2)
z = x + y
print(x)
print(y)
print(z)
z = x - y
print(z)
w = torch.rand(2,2)
print(w)
w.add_(x) #in place addition
print(w)
z = x * y
print(z)
z = x / y
print(z)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.6318, 0.6921],
        [0.7755, 0.6996]])
tensor([[1.6318, 1.6921],
        [1.7755, 1.6996]])
tensor([[0.3682, 0.3079],
        [0.2245, 0.3004]])
tensor([[0.8208, 0.5684],
        [0.5763, 0.0125]])
tensor([[1.8208, 1.5684],
        [1.5763, 1.0125]])
tensor([[0.6318, 0.6921],
        [0.7755, 0.6996]])
tensor([[1.5827, 1.4448],
        [1.2895, 1.4293]])


In [ ]:
x = torch.rand(4,3)
print(x)
print ("x[:, 0] : ", x[:, 0]) #all rows, 0th column
print ("x[0, :] : ", x[0, :]) #0th rows, all column
print ("x[1, 1] : ", x[1, 1]) #element at 1,1

print ("x[1, 1].item() : ", x[1, 1].item()) #get the value as a python number

tensor([[0.9810, 0.7951, 0.5817],
        [0.3594, 0.9235, 0.3651],
        [0.4545, 0.9434, 0.5145],
        [0.8227, 0.7402, 0.8970]])
x[:, 0] :  tensor([0.9810, 0.3594, 0.4545, 0.8227])
x[0, :] :  tensor([0.9810, 0.7951, 0.5817])
x[1, 1] :  tensor(0.9235)
x[1, 1].item() :  0.9234743118286133


In [ ]:
x = torch.rand(4,4)
y = x.view(16)
print(x)
print(y)
y = x.view(-1, 8) #the size -1 is inferred from other dimensions
print(y)

tensor([[0.0405, 0.4061, 0.8360, 0.5800],
        [0.0385, 0.9527, 0.2925, 0.1204],
        [0.0563, 0.3839, 0.5831, 0.9223],
        [0.0023, 0.9584, 0.5333, 0.1493]])
tensor([0.0405, 0.4061, 0.8360, 0.5800, 0.0385, 0.9527, 0.2925, 0.1204, 0.0563,
        0.3839, 0.5831, 0.9223, 0.0023, 0.9584, 0.5333, 0.1493])
tensor([[0.0405, 0.4061, 0.8360, 0.5800, 0.0385, 0.9527, 0.2925, 0.1204],
        [0.0563, 0.3839, 0.5831, 0.9223, 0.0023, 0.9584, 0.5333, 0.1493]])


In [ ]:
a = torch.ones(4)
print(a)

b = a.numpy() #converting to numpy array
print(b)
print(type(b))

a.add_(1)
print(a)
print(b) #changing one changes the other too

tensor([1., 1., 1., 1.])
[1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


In [ ]:
import numpy as np

a = np.ones(4)
b = torch.from_numpy(a) #share same memory as a, changing one will also change the other
c = torch.tensor(a) #real copy of a, don't affect each other

print(a)
print(b)
print(c)
a += 1
print(b)
print(c)

[1. 1. 1. 1.]
tensor([1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1.], dtype=torch.float64)
tensor([2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
x = torch.rand(2,3, requires_grad=True)
y = x + 2
z = 4 * y * y
print(x)
print(y)
print(y.grad_fn)
print(z)
z = z.mean()
print(z)

tensor([[0.2328, 0.4462, 0.0274],
        [0.2880, 0.4272, 0.5217]], requires_grad=True)
tensor([[2.2328, 2.4462, 2.0274],
        [2.2880, 2.4272, 2.5217]], grad_fn=<AddBackward0>)
tensor([[19.9413, 23.9354, 16.4418],
        [20.9401, 23.5658, 25.4356]], grad_fn=<MulBackward0>)
tensor(21.7100, grad_fn=<MeanBackward0>)


In [ ]:
print(x.grad)
z.backward()
print(x.grad)
print(y.grad)

None
tensor([[2.9770, 3.2616, 2.7032],
        [3.0507, 3.2363, 3.3623]])
None


/tmp/ipython-input-10-3035338691.py:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(y.grad)


In [ ]:
import torch

X = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = torch.float32)
Y = torch.tensor([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], dtype = torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

def forward(x):
    return w*x

def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

X_test = 5.0

print(f'Prediction before training: f({X_test}) = {forward(X_test).item():.3f}')

Prediction before training: f(5.0) = 0.000


In [ ]:
learning_rate = 0.01
n_epochs = 100

for epoch in range(n_epochs):
    y_pred = forward(X)
    l = loss(Y, y_pred)

    l.backward()

    with torch.no_grad():
      w -= w.grad * learning_rate

    w.grad.zero_()


    print(f'epoch {epoch+1}, w = {w.item():.3f}, loss = {l.item():.3f}')
    if l.item() == 0:
      break

print(f'Prediction after training: f({X_test}) = {forward(X_test).item():.3f}')

epoch 1, w = 2.000, loss = 0.000
Prediction after training: f(5.0) = 10.000


In [ ]:
import torch
import torch.nn as nn

X = torch.tensor([[1], [2], [3], [4], [5], [6], [7], [8]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8], [10], [12], [14], [16]], dtype=torch.float32)

n_samples, n_features = X.shape
print(f'n_samples = {n_samples}, n_features = {n_features}')

X_test = torch.tensor([5], dtype=torch.float32)

In [ ]:
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        self.lin = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.lin(x)


input_size, output_size = n_features, n_features

model = LinearRegression(input_size, output_size)

print(f'Prediction before training: f({X_test.item()}) = {model(X_test).item():.3f}')


learning_rate = 0.01
n_epochs = 100

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)


for epoch in range(n_epochs):

    y_predicted = model(X)
    l = loss(Y, y_predicted)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()

    if (epoch+1) % 10 == 0:
        w, b = model.parameters()
        print('epoch ', epoch+1, ': w = ', w[0][0].item(), ' loss = ', l.item())

print(f'Prediction after training: f({X_test.item()}) = {model(X_test).item():.3f}')

In [ ]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

input_size = 784
hidden_size = 500
num_classes = 10
num_epochs = 2
batch_size = 100
learning_rate = 0.001


train_dataset = torchvision.datasets.MNIST(root='./data',
                                           train=True,
                                           transform=transforms.ToTensor(),
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='./data',
                                          train=False,
                                          transform=transforms.ToTensor())

train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=batch_size,
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                          batch_size=batch_size,
                                          shuffle=False)

examples = iter(test_loader)
example_data, example_targets = examples.next()

for i in range(6):
    plt.subplot(2,3,i+1)
    plt.imshow(example_data[i][0], cmap='gray')
plt.show()